-- Seed data for Recruit360 ECNL clubs
-- Generated from ecnl_clubs.json
-- NOTE: Run schema migration first to allow ECNL division:
--   ALTER TABLE colleges DROP CONSTRAINT IF EXISTS colleges_division_check;
--   ALTER TABLE colleges ADD CONSTRAINT colleges_division_check CHECK (division IN ('D1', 'D2', 'D3', 'ECNL'));

-- Migration: update division check constraint
ALTER TABLE colleges DROP CONSTRAINT IF EXISTS colleges_division_check;
ALTER TABLE colleges ADD CONSTRAINT colleges_division_check CHECK (division IN ('D1', 'D2', 'D3', 'ECNL'));

-- Insert ECNL clubs
INSERT INTO colleges (id, name, division, conference, city, state, region, lat, lng, website) VALUES
('ac-connecticut', 'AC Connecticut', 'ECNL', 'Northeast & Mid-Atlantic', '', 'CT', 'Northeast', 41.5573837, -72.1169431, 'https://www.acconnecticut.com/contactus'),
('alabama-fc', 'Alabama FC', 'ECNL', 'Southeast', '', 'AL', 'Southeast', 33.9260807, -86.0155582, 'https://www.birminghamunited.com/about-alabama-fc/'),
('albion-hurricanes', 'Albion Hurricanes', 'ECNL', 'Texas & South Central', '', '', 'Southwest', 0, 0, 'https://www.albionhurricanes.org/'),
('arizona-arsenal', 'Arizona Arsenal', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://www.azarsenalsc.org/contact/'),
('arsenal-fc', 'Arsenal FC', 'ECNL', 'California (South & North)', '', 'CA', 'West', 33.8979123, -117.5731446, 'https://www.arsenal.com/the-club/contact-arsenal'),
('atlanta-fire', 'Atlanta Fire', 'ECNL', 'Southeast', '', 'GA', 'Southeast', 33.7103888, -84.3813458, 'https://www.atlantaunitedsoccer.com/'),
('beach-fc', 'Beach FC', 'ECNL', 'California (South & North)', '', 'CA', 'West', 36.8465642, -121.8046101, 'https://www.beachfc.com/'),
('bethesda-sc', 'Bethesda SC', 'ECNL', 'Northeast & Mid-Atlantic', '', 'SC', 'Northeast', 34.6412668, -80.0475656, 'https://www.bethesdasoccer.org/'),
('boise-thorns', 'Boise Thorns', 'ECNL', 'West & Northwest', '', 'ID', 'West', 43.548498, -116.3431306, 'https://boisetimbersthorns.org/contact-us/'),
('boise-timbers', 'Boise Timbers', 'ECNL', 'West & Northwest', '', 'ID', 'West', 43.5726978, -116.1359797, 'https://boisetimbersthorns.org/contact-us/'),
('capital-fc', 'Capital FC', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://www.cfcsalem.com/'),
('cesa', 'CESA', 'ECNL', 'Southeast', '', '', 'Southeast', 0, 0, 'http://carolinaelitesc.com/'),
('charlotte-independence', 'Charlotte Independence', 'ECNL', 'Southeast', '', 'NC', 'Southeast', 35.1372226, -80.7170502, 'https://www.independencesoccer.club/'),
('charlotte-sa', 'Charlotte SA', 'ECNL', 'Southeast', '', 'WA', 'Southeast', 38.8881013, -76.9951879, 'https://charlottesocceracademy.com/'),
('cleveland-force', 'Cleveland Force', 'ECNL', 'Midwest', '', 'OH', 'Midwest', 41.4414656, -81.6277015, 'https://www.clevelandforcesc.com/'),
('colorado-rush', 'Colorado Rush', 'ECNL', 'West & Northwest', '', 'CO', 'West', 38.8399934, -104.0921799, 'https://www.coloradorush.com/contact-us'),
('concorde-fire', 'Concorde Fire', 'ECNL', 'Southeast', '', 'OK', 'Southeast', 35.6403417, -97.4836314, 'https://concordefire.com/contact-us'),
('crossfire-premier', 'Crossfire Premier', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://www.crossfiresoccer.org/about-us/contact/'),
('crossfire-united', 'Crossfire United', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://www.crossfiresoccer.org/'),
('d-feeters-kicks-sc', 'D’Feeters Kicks SC', 'ECNL', 'Texas & South Central', '', '', 'Southwest', 0, 0, 'https://playclubsoccer.org/club/dksc'),
('dallas-texans', 'Dallas Texans', 'ECNL', 'Texas & South Central', '', 'TX', 'Southwest', 32.9212104, -96.9233597, 'https://dallastexans.com/resources/contact-us/'),
('davis-legacy', 'Davis Legacy', 'ECNL', 'California (South & North)', '', 'UT', 'West', 41.0631733, -111.9436431, 'https://playclubsoccer.org/club/davis-legacy'),
('de-anza-force', 'De Anza Force', 'ECNL', 'California (South & North)', '', '', 'West', 0, 0, 'https://www.deanzaforce.org/about-us/contact-force'),
('del-mar-sharks', 'Del Mar Sharks', 'ECNL', 'California (South & North)', '', '', 'West', 0, 0, 'https://legendsfcsd.com/'),
('delaware-fc', 'Delaware FC', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://delawarefc.org/'),
('eagles-sc', 'Eagles SC', 'ECNL', 'California (South & North)', '', 'CA', 'West', 33.2880928, -116.5941849, 'https://eaglessc.sprocketsports.com/'),
('east-coast-fc', 'East Coast FC', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://playclubsoccer.org/club/east-coast-fc'),
('eastside-fc', 'Eastside FC', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://www.eastsidefc.org/contact'),
('eclipse-select', 'Eclipse Select', 'ECNL', 'Midwest', '', '', 'Midwest', 0, 0, 'https://www.eclipseselect.org/'),
('eugene-metro', 'Eugene Metro', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://emfc.org/'),
('fc-bucks', 'FC Bucks', 'ECNL', 'Northeast & Mid-Atlantic', '', 'MI', 'Northeast', 44.7480703, -84.5700241, 'https://www.fcbucks.com/contact-us-2/'),
('fc-dallas', 'FC Dallas', 'ECNL', 'Texas & South Central', '', 'TX', 'Southwest', 32.7762719, -96.7968559, 'https://www.fcdallas.com/'),
('fc-delco', 'FC Delco', 'ECNL', 'Northeast & Mid-Atlantic', '', 'NC', 'Northeast', 34.3157241, -78.2247211, 'https://fcdelco.org/administration/contact-us/'),
('fc-portland', 'FC Portland', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://www.fcportland.org/contact'),
('fc-pride', 'FC Pride', 'ECNL', 'Midwest', '', '', 'Midwest', 0, 0, 'https://fcpride.org/'),
('fc-stars', 'FC Stars', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://fcstars.com/about-us/contact-us/'),
('florida-elite', 'Florida Elite', 'ECNL', 'Southeast', '', 'FL', 'Southeast', 29.1290911, -81.0010027, 'https://sports.bluesombrero.com/Default.aspx?tabid=754747'),
('florida-kraze-krush', 'Florida Kraze Krush', 'ECNL', 'Southeast', '', '', 'Southeast', 0, 0, 'https://floridakrazekrush.com/contact-fkk/'),
('fsa-fc', 'FSA FC', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://fsafc.com/contact-us/'),
('gretna-elite-academy', 'Gretna Elite Academy', 'ECNL', 'Midwest', '', '', 'Midwest', 0, 0, 'https://www.gretnaeliteacademy.com/contact/'),
('gsa', 'GSA', 'ECNL', 'Southeast', '', '', 'Southeast', 0, 0, 'https://www.gsasoccer.com/'),
('heat-fc', 'Heat FC', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://www.fresnoheatfc.com/'),
('idaho-rush', 'Idaho Rush', 'ECNL', 'West & Northwest', '', 'ID', 'West', 45.0974012, -114.9344641, 'https://www.idahorush.com/contact'),
('indiana-fire', 'Indiana Fire', 'ECNL', 'Midwest', '', 'IN', 'Midwest', 39.7690881, -86.1638704, 'https://www.indyelevenspirit.org/Default.aspx?tabid=160784'),
('internationals-sc', 'Internationals SC', 'ECNL', 'Midwest', '', '', 'Midwest', 0, 0, 'https://www.internationalssoccer.com/'),
('jacksonville-fc', 'Jacksonville FC', 'ECNL', 'Southeast', '', 'FL', 'Southeast', 30.4703156, -81.5639875, 'https://jfcsoccer.com/contact'),
('kansas-city-athletics', 'Kansas City Athletics', 'ECNL', 'Midwest', '', 'KS', 'Midwest', 39.1003365, -94.5853024, 'https://www.athleticskc.com/'),
('kansas-rush', 'Kansas Rush', 'ECNL', 'Midwest', '', 'KS', 'Midwest', 38.5047752, -99.309214, 'https://www.kansasrush.com/'),
('kings-hammer', 'Kings Hammer', 'ECNL', 'Midwest', '', '', 'Midwest', 0, 0, 'https://kingshammer.com/contact/'),
('la-breakers', 'LA Breakers', 'ECNL', 'California (South & North)', '', 'CA', 'West', 33.5819617, -117.7374532, 'https://labreakersfc.com/'),
('la-roca', 'La Roca', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://larocafc.com/contact/'),
('lafc-slammers', 'LAFC Slammers', 'ECNL', 'California (South & North)', '', '', 'West', 0, 0, 'https://slammersfc.org/contact/'),
('legends-fc', 'Legends FC', 'ECNL', 'California (South & North)', '', 'CA', 'West', 34.3243072, -118.4942347, 'https://www.legendsfc.net/contact-us'),
('louisiana-fire', 'Louisiana Fire', 'ECNL', 'Southeast', '', 'LA', 'Southeast', 30.3687638, -91.1603972, 'https://www.lafiresoccer.com/'),
('marin-fc', 'Marin FC', 'ECNL', 'California (South & North)', '', 'CA', 'West', 33.6575745, -117.6838098, 'https://marinfc.org/contact-us/'),
('maryland-united-fc', 'Maryland United FC', 'ECNL', 'Northeast & Mid-Atlantic', '', 'MD', 'Northeast', 0, 0, 'https://mdunitedfc.org/contact/'),
('match-fit-academy', 'Match Fit Academy', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://tshq.bluesombrero.com/Default.aspx?tabid=1753820'),
('michigan-hawks', 'Michigan Hawks', 'ECNL', 'Midwest', '', 'MI', 'Midwest', 45.3019566, -83.8874982, 'https://hawks.soccer/contact/'),
('midwest-united', 'Midwest United', 'ECNL', 'Midwest', '', 'MI', 'Midwest', 42.8972788, -85.5815032, 'https://midwestunitedfc.com/'),
('minnesota-thunder-academy', 'Minnesota Thunder Academy', 'ECNL', 'Midwest', '', 'MN', 'Midwest', 44.8606526, -93.4005721, 'https://mnthunderacademy.org/contact-us/'),
('missouri-rush', 'Missouri Rush', 'ECNL', 'Midwest', '', 'MO', 'Midwest', 38.7447238, -90.7538195, 'https://www.morushsoccer.com/contact-us'),
('mustang-sc', 'Mustang SC', 'ECNL', 'California (South & North)', '', 'CA', 'West', 34.3248935, -118.468182, 'https://mustangsoccer.com/contact-us'),
('mvla', 'MVLA', 'ECNL', 'California (South & North)', '', '', 'West', 0, 0, 'https://www.mvlasc.org/'),
('nationals-sc', 'Nationals SC', 'ECNL', 'Midwest', '', '', 'Midwest', 0, 0, 'https://www.nationalssoccer.com/'),
('nc-courage', 'NC Courage', 'ECNL', 'Southeast', '', 'NC', 'Southeast', 35.8955774, -78.5844347, 'https://www.nccourage.com/contact-us'),
('nc-fusion', 'NC Fusion', 'ECNL', 'Southeast', '', 'NC', 'Southeast', 35.0536817, -78.8810819, 'https://www.ncfusion.org/'),
('ncfc-youth', 'NCFC Youth', 'ECNL', 'Southeast', '', 'NC', 'Southeast', 35.8844007, -78.5492123, 'https://www.ncfcyouth.com/'),
('ohio-elite', 'Ohio Elite', 'ECNL', 'Midwest', '', 'OH', 'Midwest', 41.5051659, -81.6332744, 'https://ohioelite.sportngin.com/page/show/3065124-contact-us'),
('ohio-premier', 'Ohio Premier', 'ECNL', 'Midwest', '', 'OH', 'Midwest', 41.0332448, -81.9006796, 'https://opsoccer.com/'),
('oklahoma-celtic', 'Oklahoma Celtic', 'ECNL', 'Texas & South Central', '', 'OK', 'Southwest', 35.4720602, -97.7593652, 'https://oklahomaceltic.com/about-us/contact-us/'),
('oklahoma-energy-fc', 'Oklahoma Energy FC', 'ECNL', 'Texas & South Central', '', 'OK', 'Southwest', 36.1906497, -95.2907489, 'https://okenergyfc.org/'),
('oregon-premier', 'Oregon Premier', 'ECNL', 'West & Northwest', '', 'OR', 'West', 45.5881655, -122.6760597, 'https://www.oregonpremierfc.com/contact-us'),
('orlando-city-youth-soccer', 'Orlando City Youth Soccer', 'ECNL', 'Southeast', '', '', 'Southeast', 0, 0, 'https://www.oss-seminole.com/contact-us'),
('pacnw', 'PacNW', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://www.pacificnorthwestsoccerclub.org/contact'),
('pda', 'PDA', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 45.5084048, -73.5665434, 'https://pdacorporation.com/ContactUs'),
('penn-fusion-sa', 'Penn Fusion SA', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://www.pennfusion.org/'),
('philadelphia-ukrainians', 'Philadelphia Ukrainians', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://ukrainiannationals.sprocketsports.com/'),
('phoenix-rising-fc', 'Phoenix Rising FC', 'ECNL', 'West & Northwest', '', 'AZ', 'West', 33.5593664, -111.8864574, 'https://www.phxrisingfc.com/contact-us/'),
('pipeline-sc', 'Pipeline SC', 'ECNL', 'Northeast & Mid-Atlantic', '', 'SC', 'Northeast', 34.8467103, -82.0107508, 'https://scpipelineandengineering.com/contact/'),
('pittsburgh-riverhounds', 'Pittsburgh Riverhounds', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://www.riverhounds.com/contact-us/'),
('pleasanton-rage', 'Pleasanton Rage', 'ECNL', 'California (South & North)', '', '', 'West', 0, 0, 'https://pleasantonrage.org/contact-us/'),
('portland-thorns-academy', 'Portland Thorns Academy', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://www.thorns.com/academy/player-interest-form'),
('psa-monmouth', 'PSA Monmouth', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://princetonsocceracademy.com/monmouth/'),
('racing-louisville-academy', 'Racing Louisville Academy', 'ECNL', 'Midwest', '', '', 'Midwest', 0, 0, 'https://www.loucityracingacademy.com/'),
('real-colorado', 'Real Colorado', 'ECNL', 'West & Northwest', '', 'CO', 'West', 39.541871, -104.8460555, 'https://www.realcolorado.net/'),
('real-so-cal', 'Real So Cal', 'ECNL', 'California (South & North)', '', '', 'West', 0, 0, 'http://realsocal.org/about-us/contact-us'),
('rebels-sc', 'Rebels SC', 'ECNL', 'California (South & North)', '', 'SC', 'West', 32.8407484, -79.8340514, 'https://rebelssoccerclub.com/home/'),
('richmond-united', 'Richmond United', 'ECNL', 'Southeast', '', '', 'Southeast', 0, 0, 'https://richmondunited.com/'),
('san-diego-surf', 'San Diego Surf', 'ECNL', 'California (South & North)', '', 'CA', 'West', 32.7087422, -117.1704417, 'https://surfsoccer.com/contact-us/'),
('san-juan-sc', 'San Juan SC', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://playclubsoccer.org/club/san-juan-soccer-club'),
('santa-rosa-united', 'Santa Rosa United', 'ECNL', 'California (South & North)', '', 'CA', 'West', 38.4589573, -122.7136164, 'https://www.srunited.com/club/contact-us/'),
('scorpions-soccer', 'Scorpions Soccer', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://www.scorpionssoccer.org/'),
('seattle-united', 'Seattle United', 'ECNL', 'West & Northwest', '', 'WA', 'West', 47.5687743, -122.3836821, 'https://www.seattleunited.com/'),
('sjeb-fc', 'SJEB FC', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://www.sjebfc.com/'),
('slammers-fc', 'Slammers FC', 'ECNL', 'California (South & North)', '', '', 'West', 0, 0, 'https://slammersfc.org/contact/'),
('slsg', 'SLSG', 'ECNL', 'Midwest', '', 'IL', 'Midwest', 38.6955607, -90.0144525, 'https://www.slsgsoccer.com/'),
('so-cal-blues', 'So Cal Blues', 'ECNL', 'California (South & North)', '', '', 'West', 0, 0, 'https://bluessoccer.com/about'),
('solar-sc', 'Solar SC', 'ECNL', 'Texas & South Central', '', '', 'Southwest', 0, 0, 'https://solarsoccerclub.net/resource-hub/contact-us/'),
('sporting-blue-valley', 'Sporting Blue Valley', 'ECNL', 'Midwest', '', '', 'Midwest', 0, 0, 'https://clubs.bluesombrero.com/Default.aspx?tabid=48597'),
('st-louis-stars', 'St. Louis Stars', 'ECNL', 'Midwest', '', 'MO', 'Midwest', 38.6317586, -90.2254759, 'https://stlstars.club/contact-us/'),
('sting-sc', 'Sting SC', 'ECNL', 'Texas & South Central', '', 'SC', 'Southwest', 32.9986606, -79.7549391, 'https://stingsoccer.com/'),
('strikers-fc', 'Strikers FC', 'ECNL', 'California (South & North)', '', '', 'West', 0, 0, 'https://www.strikersfc.com/'),
('sunrise-prime', 'Sunrise Prime', 'ECNL', 'Southeast', '', '', 'Southeast', 0, 0, 'https://www.fc-prime.com/regions-broward'),
('susa-fc', 'SUSA FC', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://www.susaacademy.com/'),
('tampa-bay-united', 'Tampa Bay United', 'ECNL', 'Southeast', '', 'FL', 'Southeast', 27.9877508, -82.5742505, 'https://tbusc.com/contact/'),
('tennessee-soccer-club', 'Tennessee Soccer Club', 'ECNL', 'Southeast', '', 'TN', 'Southeast', 35.7376237, -83.952697, 'https://tennesseesoccerclub.org/locations/'),
('tulsa-sc', 'Tulsa SC', 'ECNL', 'Texas & South Central', '', 'OK', 'Southwest', 36.1563122, -95.9927516, 'https://www.tulsasc.com/contact-us/'),
('ufa', 'UFA', 'ECNL', 'Southeast', '', '', 'Southeast', 0, 0, 'https://www.unitedfa.org/'),
('utah-avalanche', 'Utah Avalanche', 'ECNL', 'West & Northwest', '', 'UT', 'West', 39.6278219, -110.7922019, 'https://utahavalanche.com/about-us/contact-us/'),
('utah-royals-fc-az', 'Utah Royals FC-AZ', 'ECNL', 'West & Northwest', '', '', 'West', 0, 0, 'https://www.royalsfcaz.com/'),
('vda', 'VDA', 'ECNL', 'Southeast', '', '', 'Southeast', 0, 0, 'https://www.vdasoccer.org/'),
('washington-premier', 'Washington Premier', 'ECNL', 'West & Northwest', '', 'WA', 'West', 0, 0, 'https://www.washingtonpremierfc.com/about-us/contact-us/'),
('western-new-york-flash', 'Western New York Flash', 'ECNL', 'Northeast & Mid-Atlantic', '', '', 'Northeast', 0, 0, 'https://wnyflash.com/academy-overview/contact'),
('wilmington-hammerheads', 'Wilmington Hammerheads', 'ECNL', 'Southeast', '', '', 'Southeast', 0, 0, 'https://www.hammerheads.soccer/contact'),
('world-class-fc', 'World Class FC', 'ECNL', 'Northeast & Mid-Atlantic', '', 'OH', 'Northeast', 40.4527032, -83.9014572, 'http://wcsocceracademy.org/contact-information/world-class-fc-contact-information/');

-- Insert ECNL contacts
INSERT INTO coaches (college_id, name, title, email, phone) VALUES
('albion-hurricanes', 'Contact', 'Club Contact', 'sgreen@albionhurricanes.org', NULL),
('albion-hurricanes', 'Contact', 'Club Contact', 'jhinfo@albionhurricanes.org', NULL),
('albion-hurricanes', 'Contact', 'Club Contact', 'tournaments@albionhurricanes.org', NULL),
('arizona-arsenal', 'Contact', 'Club Contact', 'arsenaltryouts@gmail.com', NULL),
('arizona-arsenal', 'Contact', 'Club Contact', 'davidbelfort@ymail.com', NULL),
('arizona-arsenal', 'Contact', 'Club Contact', 'tannafinnvik@azarsenalsc.org', NULL),
('arsenal-fc', 'Contact', 'Club Contact', 'partnerships@arsenal.co.uk', NULL),
('arsenal-fc', 'Contact', 'Club Contact', 'customerservice@arsenaldirect.co.uk', NULL),
('atlanta-fire', 'Contact', 'Club Contact', 'kim.hall@atlantaunitedsoccer.com', NULL),
('bethesda-sc', 'Contact', 'Club Contact', 'office@bethesdasoccer.org', NULL),
('boise-thorns', 'Contact', 'Club Contact', 'registrar@boisetimbersthorns.org', NULL),
('boise-timbers', 'Contact', 'Club Contact', 'registrar@boisetimbersthorns.org', NULL),
('capital-fc', 'Contact', 'Club Contact', 'office@cfcsalem.com', NULL),
('cesa', 'Contact', 'Club Contact', 'info@carolinaelitesc.com', NULL),
('charlotte-sa', 'Contact', 'Club Contact', 'admin@charlottesocceracademy.com', NULL),
('cleveland-force', 'Contact', 'Club Contact', 'Info@ClevelandForceSC.com', NULL),
('cleveland-force', 'Contact', 'Club Contact', 'reilee@force-sports.com', NULL),
('cleveland-force', 'Contact', 'Club Contact', 'CJ@Force-Sports.com', NULL),
('colorado-rush', 'Contact', 'Club Contact', 'info@coloradorush.com', NULL),
('concorde-fire', 'Contact', 'Club Contact', 'info@concordefire.com', NULL),
('dallas-texans', 'Contact', 'Club Contact', 'hassan1@prodigy.net', NULL),
('delaware-fc', 'Contact', 'Club Contact', 'defc@delawarefc.org', NULL),
('eagles-sc', 'Contact', 'Club Contact', 'info@eaglessc.com', NULL),
('eastside-fc', 'Contact', 'Club Contact', 'info@eastsidefc.org', NULL),
('eastside-fc', 'Contact', 'Club Contact', 'media@eastsidefc.org', NULL),
('fc-bucks', 'Contact', 'Club Contact', 'admin@crusa.net', NULL),
('fc-bucks', 'Contact', 'Club Contact', 'connect@crusa.net', NULL),
('fc-bucks', 'Contact', 'Club Contact', 'crusapresident@crusa.net', NULL),
('fc-bucks', 'Contact', 'Club Contact', 'supervisor@crusa.net', NULL),
('fc-bucks', 'Contact', 'Club Contact', 'girlsdoc@crusa.net', NULL),
('fc-dallas', 'Contact', 'Club Contact', 'feedback@fcdallas.com', NULL),
('fc-delco', 'Contact', 'Club Contact', 'jeff@fcdelco.org', NULL),
('fc-portland', 'Contact', 'Club Contact', 'louis.tanguy@fcportland.org', NULL),
('fc-stars', 'Contact', 'Club Contact', 'info@fcstars.com', NULL),
('florida-elite', 'Contact', 'Club Contact', 'info@FloridaEliteSA.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'koettl@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'dgorrick@floridarazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'dpetersen@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'mhansen@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'idcamp@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'gbarbosa@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'adensberger@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'ovallejo@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'info@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'hmenzies@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'lmarcus@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'dphillips@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'javallone@floridakrazekrush.com', NULL),
('florida-kraze-krush', 'Contact', 'Club Contact', 'gmikalsen@floridakrazekrush.com', NULL),
('fsa-fc', 'Contact', 'Club Contact', 'clubadmin@fsafcunited.com', NULL),
('gretna-elite-academy', 'Contact', 'Club Contact', 'chris.dunford@gretnaeliteacademy.com', NULL),
('gretna-elite-academy', 'Contact', 'Club Contact', 'raphael.martinez@gretnaeliteacademy.com', NULL),
('gretna-elite-academy', 'Contact', 'Club Contact', 'clubadmin@gretnaeliteacademy.com', NULL),
('gretna-elite-academy', 'Contact', 'Club Contact', 'greg.jarosik@gretnaeliteacademy.com', NULL),
('gretna-elite-academy', 'Contact', 'Club Contact', 'mitch.kavanagh@gretnaeliteacademy.com', NULL),
('gretna-elite-academy', 'Contact', 'Club Contact', 'jono.callaghan@gretnaeliteacademy.com', NULL),
('heat-fc', 'Contact', 'Club Contact', 'admin@fresnoheatfc.com', NULL),
('idaho-rush', 'Contact', 'Club Contact', 'info@hawaiirush.com', NULL),
('idaho-rush', 'Contact', 'Club Contact', 'info@idahorush.com', NULL),
('indiana-fire', 'Contact', 'Club Contact', 'fcs11info@gmail.com', NULL),
('indiana-fire', 'Contact', 'Club Contact', 'info@indianafirejuniorssouth.com', NULL),
('internationals-sc', 'Contact', 'Club Contact', 'ksarver@gmail.com', NULL),
('jacksonville-fc', 'Contact', 'Club Contact', 'office@jfcsoccer.com', NULL),
('kansas-rush', 'Contact', 'Club Contact', 'officestaff@kansasrush.com', NULL),
('kings-hammer', 'Contact', 'Club Contact', 'info@kingshammer.com', NULL),
('la-breakers', 'Contact', 'Club Contact', 'info@labreakersfc.com', NULL),
('legends-fc', 'Contact', 'Club Contact', 'mama.hodges@legendsfc.net', NULL),
('legends-fc', 'Contact', 'Club Contact', 'tsklar@legendsfc.net', NULL),
('louisiana-fire', 'Contact', 'Club Contact', 'info@lafiresoccer.com', NULL),
('marin-fc', 'Contact', 'Club Contact', 'admin@marinfc.com', NULL),
('maryland-united-fc', 'Contact', 'Club Contact', 'steve.campbell@mdunitedfc.org', NULL),
('match-fit-academy', 'Contact', 'Club Contact', 'info@matchfitacademy.net', NULL),
('michigan-hawks', 'Contact', 'Club Contact', 'michele@hawks.soccer', NULL),
('michigan-hawks', 'Contact', 'Club Contact', 'doug@hawks.soccer', NULL),
('midwest-united', 'Contact', 'Club Contact', 'info@midwestunitedfc.com', NULL),
('minnesota-thunder-academy', 'Contact', 'Club Contact', 'admin@mnthunderacademy.org', NULL),
('missouri-rush', 'Contact', 'Club Contact', 'info@morushsoccer.com', NULL),
('mustang-sc', 'Contact', 'Club Contact', 'media@mustangsoccer.com', NULL),
('mvla', 'Contact', 'Club Contact', 'admin@mvlasc.org', NULL),
('nationals-sc', 'Contact', 'Club Contact', 'info@nationalssoccer.com', NULL),
('nc-fusion', 'Contact', 'Club Contact', 'info@ncfusion.org', NULL),
('ncfc-youth', 'Contact', 'Club Contact', 'info@NCFCYouth.com', NULL),
('oklahoma-celtic', 'Contact', 'Club Contact', 'administrator@oklahomaceltic.com', NULL),
('oklahoma-energy-fc', 'Contact', 'Club Contact', 'info@okenergyfc.org', NULL),
('oregon-premier', 'Contact', 'Club Contact', 'info@oregonpremierfc.com', NULL),
('orlando-city-youth-soccer', 'Contact', 'Club Contact', 'Admin@ocyouthsoccer.com', NULL),
('pda', 'Contact', 'Club Contact', 'rkstaley@alacritysolutions.com', NULL),
('pda', 'Contact', 'Club Contact', 'rjpicone@alacritysolutions.com', NULL),
('pda', 'Contact', 'Club Contact', 'csc_sas@alacritysolutions.com', NULL),
('pda', 'Contact', 'Club Contact', 'bsoli@alacritysolutions.com', NULL),
('pda', 'Contact', 'Club Contact', 'vvettese@alacritysolutions.com', NULL),
('pda', 'Contact', 'Club Contact', 'jdstephens@alacritysolutions.com', NULL),
('pda', 'Contact', 'Club Contact', 'tvoglesong@alacritysolutions.com', NULL),
('pda', 'Contact', 'Club Contact', 'jbowman@alacritysolutions.com', NULL),
('pda', 'Contact', 'Club Contact', 'aborninkhof@alacritysolutions.com', NULL),
('penn-fusion-sa', 'Contact', 'Club Contact', 'jscott@pennfusion.org', NULL),
('philadelphia-ukrainians', 'Contact', 'Club Contact', 'info@ukrainiannationals.com', NULL),
('phoenix-rising-fc', 'Contact', 'Club Contact', 'info@phxrisingfc.com', NULL),
('pipeline-sc', 'Contact', 'Club Contact', 'santino@pipelinesc.com', NULL),
('portland-thorns-academy', 'Contact', 'Club Contact', 'portlandthornsacademy@gmail.com', NULL),
('real-colorado', 'Contact', 'Club Contact', 'realcares@realcolorado.net', NULL),
('real-colorado', 'Contact', 'Club Contact', 'SobyG@realcolorado.net', NULL),
('real-so-cal', 'Contact', 'Club Contact', 'Paul.clifton@lafcsocal.org', NULL),
('real-so-cal', 'Contact', 'Club Contact', 'Richard.Simms@lafcsocal.org', NULL),
('real-so-cal', 'Contact', 'Club Contact', 'Alberto.Bru@lafcsocal.org', NULL),
('real-so-cal', 'Contact', 'Club Contact', 'info@lafcsocal.org', NULL),
('real-so-cal', 'Contact', 'Club Contact', 'Zach.Feldman@lafcsocal.org', NULL),
('richmond-united', 'Contact', 'Club Contact', 'communications@richmondunited.com', NULL),
('san-diego-surf', 'Contact', 'Club Contact', 'info@surfsoccer.com', NULL),
('san-juan-sc', 'Contact', 'Club Contact', 'clubadmin@sanjuansoccer.org', NULL),
('scorpions-soccer', 'Contact', 'Club Contact', 'info@scorpionssoccer.org', NULL),
('seattle-united', 'Contact', 'Club Contact', 'info@seattleunited.com', NULL),
('sjeb-fc', 'Contact', 'Club Contact', 'bill@sjebfc.com', NULL),
('sjeb-fc', 'Contact', 'Club Contact', 'SJEBFOOTBALL@GMAIL.COM', NULL),
('sjeb-fc', 'Contact', 'Club Contact', 'jeff@sjebfc.com', NULL),
('sjeb-fc', 'Contact', 'Club Contact', 'wayne@sjebfc.com', NULL),
('sjeb-fc', 'Contact', 'Club Contact', 'wbshute@njrush.com', NULL),
('solar-sc', 'Contact', 'Club Contact', 'admin@solarsoccerclub.net', NULL),
('st-louis-stars', 'Contact', 'Club Contact', 'Hasan@stlstars.club', NULL),
('st-louis-stars', 'Contact', 'Club Contact', 'Andrew@stlstars.club', NULL),
('st-louis-stars', 'Contact', 'Club Contact', 'Hutch@stlstars.club', NULL),
('st-louis-stars', 'Contact', 'Club Contact', 'ryanwerk@gmail.com', NULL),
('sunrise-prime', 'Contact', 'Club Contact', 'Aingham@fc-prime.com', NULL),
('sunrise-prime', 'Contact', 'Club Contact', 'Cyibirin@fc-prime.cm', NULL),
('sunrise-prime', 'Contact', 'Club Contact', 'Lbrown@fc-prime.com', NULL),
('sunrise-prime', 'Contact', 'Club Contact', 'Jhenao@fc-prime.com', NULL),
('sunrise-prime', 'Contact', 'Club Contact', 'admin@fc-prime.com', NULL),
('sunrise-prime', 'Contact', 'Club Contact', 'acamacho@fc-prime.com', NULL),
('sunrise-prime', 'Contact', 'Club Contact', 'jburaty@fc-prime.com', NULL),
('susa-fc', 'Contact', 'Club Contact', 'LTRAYPHOTOGRAPHY@GMAIL.COM', NULL),
('tampa-bay-united', 'Contact', 'Club Contact', 'info@tbusc.com', NULL),
('tennessee-soccer-club', 'Contact', 'Club Contact', 'info@tennesseesoccerclub.org', NULL),
('tulsa-sc', 'Contact', 'Club Contact', 'support@tulsasc.com', NULL),
('ufa', 'Contact', 'Club Contact', 'mountains@unitedfa.org', NULL),
('ufa', 'Contact', 'Club Contact', 'loganville@unitedfa.org', NULL),
('ufa', 'Contact', 'Club Contact', 'southgeorgia@unitedfa.org', NULL),
('ufa', 'Contact', 'Club Contact', 'forsyth@unitedfa.org', NULL),
('ufa', 'Contact', 'Club Contact', 'norcross@unitedfa.org', NULL),
('ufa', 'Contact', 'Club Contact', 'lawrenceville@unitedfa.org', NULL),
('utah-royals-fc-az', 'Contact', 'Club Contact', 'troberts@royalsfcaz.com', NULL),
('vda', 'Contact', 'Club Contact', 'admin@vdasoccer.org', NULL),
('western-new-york-flash', 'Contact', 'Club Contact', 'rjackman@wnyflashsoccer.com', NULL),
('western-new-york-flash', 'Contact', 'Club Contact', 'karaujo@wnyflashsoccer.com', NULL),
('western-new-york-flash', 'Contact', 'Club Contact', 'rcurtis@wnyflashsoccer.com', NULL),
('western-new-york-flash', 'Contact', 'Club Contact', 'pwhitcomb@wnyflashsoccer.com', NULL),
('western-new-york-flash', 'Contact', 'Club Contact', 'bwolanski@wnyflashsoccer.com', NULL),
('western-new-york-flash', 'Contact', 'Club Contact', 'bsteele@wnyflashsoccer.com', NULL),
('western-new-york-flash', 'Contact', 'Club Contact', 'edade@wnyflashsoccer.com', NULL),
('western-new-york-flash', 'Contact', 'Club Contact', 'alines@wnyflashsoccer.com', NULL),
('western-new-york-flash', 'Contact', 'Club Contact', 'bpedezert@wnyflashsoccer.com', NULL),
('western-new-york-flash', 'Contact', 'Club Contact', 'communications@wnyflashsoccer.com', NULL),
('world-class-fc', 'Contact', 'Club Contact', 'info@wcsocceracademy.org', NULL),
('world-class-fc', 'Contact', 'Club Contact', 'uniforms@wcsocceracademy.org', NULL),
('world-class-fc', 'Contact', 'Club Contact', 'registrar@wcsocceracademy.org', NULL),
('world-class-fc', 'Contact', 'Club Contact', 'boysdoc@wcsocceracademy.org', NULL),
('world-class-fc', 'Contact', 'Club Contact', 'girlsdoc@wcsocceracademy.org', NULL),
('world-class-fc', 'Contact', 'Club Contact', 'wcfcjj@gmail.com', NULL);

-- Done!
-- Total ECNL clubs: 115
-- Total contacts: 157
