const fs = require('fs');
const path = require('path');

// Map cities to states (based on location.csv data)
const cityToState = {
  "Abilene": "TX",
  "Normal": "AL",
  "Montgomery": "AL",
  "Lorman": "MS",
  "Washington": "DC",
  "Boone": "NC",
  "Tempe": "AZ",
  "Jonesboro": "AR",
  "Auburn": "AL",
  "Clarksville": "TN",
  "Muncie": "IN",
  "Waco": "TX",
  "Louisville": "KY",
  "Nashville": "TN",
  "Daytona Beach": "FL",
  "Boise": "ID",
  "Chestnut Hill": "MA",
  "Boston": "MA",
  "Bowling Green": "OH",
  "Peoria": "IL",
  "Provo": "UT",
  "Providence": "RI",
  "Smithfield": "RI",
  "Lewisburg": "PA",
  "Indianapolis": "IN",
  "Riverside": "CA",
  "San Luis Obispo": "CA",
  "Bakersfield": "CA",
  "Fresno": "CA",
  "Fullerton": "CA",
  "Long Beach": "CA",
  "Northridge": "CA",
  "Sacramento": "CA",
  "Buies Creek": "NC",
  "Buffalo": "NY",
  "New Britain": "CT",
  "Mount Pleasant": "MI",
  "North Charleston": "SC",
  "Chicago": "IL",
  "Clemson": "SC",
  "Cleveland": "OH",
  "Conway": "SC",
  "Hamilton": "NY",
  "Charleston": "SC",
  "Worcester": "MA",
  "Fort Collins": "CO",
  "New York": "NY",
  "Baltimore": "MD",
  "Ithaca": "NY",
  "Omaha": "NE",
  "Hanover": "NH",
  "Davidson": "NC",
  "Dover": "DE",
  "Des Moines": "IA",
  "Philadelphia": "PA",
  "Durham": "NC",
  "Pittsburgh": "PA",
  "Greenville": "NC",
  "Richmond": "KY",
  "Ypsilanti": "MI",
  "Cheney": "WA",
  "Johnson City": "TN",
  "Commerce": "TX",
  "Elon": "NC",
  "Fairfield": "CT",
  "Hackensack": "NJ",
  "Tallahassee": "FL",
  "Boca Raton": "FL",
  "Fort Myers": "FL",
  "Miami": "FL",
  "Bronx": "NY",
  "Boiling Springs": "NC",
  "Fairfax": "VA",
  "Atlanta": "GA",
  "Statesboro": "GA",
  "Spokane": "WA",
  "Grambling": "LA",
  "Phoenix": "AZ",
  "Hampton": "VA",
  "Cambridge": "MA",
  "High Point": "NC",
  "Hempstead": "NY",
  "Houston": "TX",
  "Pocatello": "ID",
  "Terre Haute": "IN",
  "Bloomington": "IN",
  "New Rochelle": "NY",
  "Ames": "IA",
  "Jackson": "MS",
  "Jacksonville": "AL",
  "Harrisonburg": "VA",
  "Manhattan": "KS",
  "Kennesaw": "GA",
  "Kent": "OH",
  "Easton": "PA",
  "Beaumont": "TX",
  "Bethlehem": "PA",
  "Stanford": "CA",
  "Lynchburg": "VA",
  "Saint Charles": "MO",
  "Brooklyn & Brookville": "NY",
  "Farmville": "VA",
  "Baton Rouge": "LA",
  "Ruston": "LA",
  "Los Angeles": "CA",
  "Riverdale": "NY",
  "Poughkeepsie": "NY",
  "Milwaukee": "WI",
  "Huntington": "WV",
  "Lake Charles": "LA",
  "Macon": "GA",
  "North Andover": "MA",
  "Oxford": "OH",
  "East Lansing": "MI",
  "Murfreesboro": "TN",
  "Mississippi State": "MS",
  "Itta Bena": "MS",
  "Springfield": "MO",
  "West Long Branch": "NJ",
  "Bozeman": "MT",
  "Morehead": "KY",
  "Emmitsburg": "MD",
  "Murray": "KY",
  "Newark": "NJ",
  "Las Cruces": "NM",
  "Niagara University": "NY",
  "Thibodaux": "LA",
  "Norfolk": "VA",
  "Greensboro": "NC",
  "Raleigh": "NC",
  "Fargo": "ND",
  "Flagstaff": "AZ",
  "DeKalb": "IL",
  "Highland Heights": "KY",
  "Natchitoches": "LA",
  "Evanston": "IL",
  "Rochester": "MI",
  "Stillwater": "OK",
  "Tulsa": "OK",
  "Corvallis": "OR",
  "Malibu": "CA",
  "Portland": "OR",
  "Prairie View": "TX",
  "Clinton": "SC",
  "Princeton": "NJ",
  "West Lafayette": "IN",
  "Fort Wayne": "IN",
  "Charlotte": "NC",
  "Hamden": "CT",
  "Radford": "VA",
  "Lawrenceville": "NJ",
  "Moon Township": "PA",
  "New Brunswick": "NJ",
  "Saint Bonaventure": "NY",
  "Loretto": "PA",
  "Queens": "NY",
  "Saint Louis": "MO",
  "Moraga": "CA",
  "Jersey City": "NJ",
  "Huntsville": "TX",
  "Homewood": "AL",
  "San Diego": "CA",
  "San Jose": "CA",
  "Santa Clara": "CA",
  "Seattle": "WA",
  "South Orange": "NJ",
  "Loudonville": "NY",
  "Orangeburg": "SC",
  "Brookings": "SD",
  "Cape Girardeau": "MO",
  "Hammond": "LA",
  "Carbondale": "IL",
  "Edwardsville": "IL",
  "Dallas": "TX",
  "Cedar City": "UT",
  "Iowa City": "IA",
  "Albany": "NY",
  "Binghamton": "NY",
  "Stony Brook": "NY",
  "Nacogdoches": "TX",
  "DeLand": "FL",
  "Syracuse": "NY",
  "Stephenville": "TX",
  "College Station": "TX",
  "Corpus Christi": "TX",
  "Fort Worth": "TX",
  "San Marcos": "TX",
  "Lubbock": "TX",
  "Williamsburg": "VA",
  "Columbus": "OH",
  "Athens": "OH",
  "University Park": "PA",
  "Akron": "OH",
  "Tuscaloosa": "AL",
  "University": "MS",
  "Albuquerque": "NM",
  "Chattanooga": "TN",
  "Martin": "TN",
  "Knoxville": "TN",
  "Arlington": "TX",
  "Austin": "TX",
  "El Paso": "TX",
  "Edinburg": "TX",
  "San Antonio": "TX",
  "Burlington": "VT",
  "Towson": "MD",
  "Troy": "AL",
  "New Orleans": "LA",
  "USAF Academy": "CO",
  "West Point": "NY",
  "Annapolis": "MD",
  "Birmingham": "AL",
  "Tucson": "AZ",
  "Fayetteville": "AR",
  "Little Rock": "AR",
  "Pine Bluff": "AR",
  "Berkeley": "CA",
  "Davis": "CA",
  "Irvine": "CA",
  "La Jolla": "CA",
  "Santa Barbara": "CA",
  "Orlando": "FL",
  "Cincinnati": "OH",
  "Boulder": "CO",
  "Storrs": "CT",
  "Dayton": "OH",
  "Denver": "CO",
  "Detroit": "MI",
  "Evansville": "IN",
  "Gainesville": "FL",
  "Honolulu": "HI",
  "Moscow": "ID",
  "Urbana": "IL",
  "Lawrence": "KS",
  "Lexington": "KY",
  "Lafayette": "LA",
  "Monroe": "LA",
  "Orono": "ME",
  "Catonsville": "MD",
  "College Park": "MD",
  "Princess Anne": "MD",
  "Amherst": "MA",
  "Lowell": "MA",
  "Memphis": "TN",
  "Coral Gables": "FL",
  "Ann Arbor": "MI",
  "Minneapolis": "MN",
  "Columbia": "MO",
  "Kansas City": "MO",
  "Missoula": "MT",
  "Lincoln": "NE",
  "Paradise": "NV",
  "Reno": "NV",
  "Chapel Hill": "NC",
  "Wilmington": "NC",
  "Grand Forks": "ND",
  "Greeley": "CO",
  "Cedar Falls": "IA",
  "Denton": "TX",
  "Notre Dame": "IN",
  "Norman": "OK",
  "Eugene": "OR",
  "Kingston": "RI",
  "Mobile": "AL",
  "Spartanburg": "SC",
  "Vermillion": "SD",
  "Tampa": "FL",
  "Stockton": "CA",
  "Toledo": "OH",
  "Salt Lake City": "UT",
  "Charlottesville": "VA",
  "Green Bay": "WI",
  "Madison": "WI",
  "Laramie": "WY",
  "Logan": "UT",
  "St. George": "UT",
  "Orem": "UT",
  "Valparaiso": "IN",
  "Villanova": "PA",
  "Blacksburg": "VA",
  "Staten Island": "NY",
  "Winston-Salem": "NC",
  "Pullman": "WA",
  "Ogden": "UT",
  "Cullowhee": "NC",
  "Macomb": "IL",
  "Kalamazoo": "MI",
  "Morgantown": "WV",
  "Wichita": "KS",
  "Rock Hill": "SC",
  "New Haven": "CT",
  "Youngstown": "OH",
  "Asheville": "NC",
  "Florence": "AL",
  "Cookeville": "TN",
  "Saint Paul": "MN",
  "San Francisco": "CA",
};

// State to region mapping
const stateToRegion = {
  // Northeast
  "CT": "Northeast", "ME": "Northeast", "MA": "Northeast", "NH": "Northeast",
  "RI": "Northeast", "VT": "Northeast", "NJ": "Northeast", "NY": "Northeast",
  "PA": "Northeast", "DC": "Northeast", "MD": "Northeast", "DE": "Northeast",

  // Southeast
  "AL": "Southeast", "AR": "Southeast", "FL": "Southeast", "GA": "Southeast",
  "KY": "Southeast", "LA": "Southeast", "MS": "Southeast", "NC": "Southeast",
  "SC": "Southeast", "TN": "Southeast", "VA": "Southeast", "WV": "Southeast",

  // Midwest
  "IL": "Midwest", "IN": "Midwest", "IA": "Midwest", "KS": "Midwest",
  "MI": "Midwest", "MN": "Midwest", "MO": "Midwest", "NE": "Midwest",
  "ND": "Midwest", "OH": "Midwest", "SD": "Midwest", "WI": "Midwest",

  // Southwest
  "AZ": "Southwest", "NM": "Southwest", "OK": "Southwest", "TX": "Southwest",

  // West
  "AK": "West", "CA": "West", "CO": "West", "HI": "West",
  "ID": "West", "MT": "West", "NV": "West", "OR": "West",
  "UT": "West", "WA": "West", "WY": "West"
};

// Read the colleges data
const collegesPath = path.join(__dirname, '../data/colleges.json');
const colleges = JSON.parse(fs.readFileSync(collegesPath, 'utf-8'));

// Add state and region to each college
const updatedColleges = colleges.map(college => {
  const state = cityToState[college.city] || "Unknown";
  const region = stateToRegion[state] || "Unknown";

  return {
    ...college,
    state,
    region
  };
});

// Check for any unknown states
const unknownCities = updatedColleges
  .filter(c => c.state === "Unknown")
  .map(c => c.city);

if (unknownCities.length > 0) {
  console.log("Cities without state mapping:", [...new Set(unknownCities)]);
}

// Write the updated data
fs.writeFileSync(collegesPath, JSON.stringify(updatedColleges, null, 2));
console.log(`Updated ${updatedColleges.length} colleges with state and region data`);
